apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: easysoftware-monitoring-deployment-autoscaler
  namespace: easysoftware
spec:
  scaleTargetRef:
    name: easysoftware-monitoring-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Shanghai
      start: 35 8 * * *
      end: 55 23 * * *
      desiredReplicas: "1"