apiVersion: apps/v1
kind: Deployment
metadata:
  name: easysoftware-monitoring-deployment
  namespace: easysoftware
spec:
  selector:
    matchLabels:
      app: easysoftware-monitoring
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: 'easysoftware'
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/agent-inject-containers: 'anitya'
        vault.hashicorp.com/secret-volume-path-config.toml: "/etc/fedora-messaging"
        vault.hashicorp.com/agent-inject-secret-config.toml: 'internal/data/infra-test/easysoftware'
        vault.hashicorp.com/agent-inject-perms-config.toml: "0400"
        vault.hashicorp.com/agent-inject-template-config.toml: |  
          {{- with secret "internal/data/infra-test/easysoftware" -}}  
          {{ .Data.data.pgConf }}
          {{- end }}
        vault.hashicorp.com/secret-volume-path-anitya.toml: "/etc/anitya"
        vault.hashicorp.com/agent-inject-secret-anitya.toml: 'internal/data/infra-test/easysoftware'
        vault.hashicorp.com/agent-inject-perms-anitya.toml: "0400"
        vault.hashicorp.com/agent-inject-template-anitya.toml: |  
          {{- with secret "internal/data/infra-test/easysoftware" -}}  
          {{ .Data.data.anityaConf }}
          {{- end }}
      labels:
        app: easysoftware-monitoring
    spec:
      serviceAccount: easysoftware
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: rabbitmq
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/rabbitmq/rabbitmq:3.8.16-management-alpine 
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: easysoftware-monitoring-secrets
              key: rabbitmq_user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: easysoftware-monitoring-secrets
              key: rabbitmq_pass                    
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5672
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5672
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: "1"
            memory: 500Mi
      - name: anitya 
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/easysoftware/easysoftware-monitoring-test:master-1184bd
        imagePullPolicy: IfNotPresent 
        env:
        - name: FLASK_APP
          value: anitya.wsgi
        - name: START_COMMAND
          value: poetry run flask run -h 0.0.0.0 
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5000
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5000
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi 
        