apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: git-access-deployment-autoscaler
  namespace: merlin
spec:
  scaleTargetRef:
    name: git-access-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Shanghai
      start: 30 8 * * *
      end: 55 23 * * *
      desiredReplicas: "1"